# Generated by Django 4.2.4 on 2024-06-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_usergroups_group_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_account',
            field=models.DateTimeField(auto_now_add=True, default='2000-11-20T15:58:44-06:00'),
            preserve_default=False,
        ),
    ]
