# Generated by Django 4.2.4 on 2024-07-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_create_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='empresa',
            new_name='enterprise',
        ),
    ]
