# Generated by Django 5.0.7 on 2024-07-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_taskstatus_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
